// DOC-DEPS: LLM.md -> docs/ACTIVITY_LEXICON.md
//
// Italian activity lexicon.
// Extracted from liveInputRules.it.ts.

import type { ActivityLexicon } from './types.js';

export const itActivityLexicon: ActivityLexicon = {
  strongPhrases: [
    'lavoro', 'lavorare', 'lavorando', 'ho lavorato',
    'sto lavorando',
    'studio', 'studiare', 'studiando', 'ho studiato',
    'ripasso', 'ripassando',
    'riunione', 'meeting', 'standup',
    'riunione con',
    'riunione di',
    'riunione per',
    'correndo', 'ho corso', 'corsa',
    'camminando', 'camminata', 'passeggiata',
    'cammino', 'camminare',
    'nuoto', 'nuotando',
    'nuotare',
    'allenamento', 'palestra', 'fitness',
    'yoga', 'pilates', 'stretching',
    'meditazione', 'meditando',
    'pranzo', 'cena', 'colazione', 'pasto',
    'bere acqua', 'bevo acqua', 'idratarmi',
    'bere te', 'preparare il te', 'fare il caffe', 'preparare il caffe',
    'riempire la borraccia', 'rabboccare la borraccia',
    'bollire l\'acqua', 'ho bollito l\'acqua',
    'fare da mangiare', 'preparare pranzo', 'preparare cena',
    'cuocere il riso', 'cucinare il riso', 'lavare il riso',
    'preparare i pasti', 'meal prep',
    'fare la zuppa', 'fare il porridge', 'cucinare la pasta', 'preparare gli ingredienti',
    'tagliare le verdure', 'lavare le verdure',
    'fare la spesa', 'comprare verdura', 'comprare verdure', 'comprare frutta', 'andare al mercato',
    'comprare latte', 'comprare pane', 'comprare uova', 'fare scorta', 'rifornire la dispensa',
    'spesa', 'supermercato', 'grocery',
    'spesa alimentare',
    'lavatrice', 'piatti', 'pulisco', 'pulire', 'pulizie',
    'fare il bucato', 'stendere i panni', 'piegare i vestiti',
    'riordinare la stanza', 'rifare il letto', 'cambiare le lenzuola',
    'passare l\'aspirapolvere', 'lavare il pavimento',
    'lavare i piatti', 'cucinare', 'sto cucinando', 'immondizia', 'buttare la spazzatura',
    'svuotare la spazzatura', 'portare fuori la spazzatura',
    'ho comprato',
    'pendolare', 'pendolando', 'metro', 'autobus', 'treno', 'guida', 'guidando',
    'lettura', 'leggere', 'leggendo', 'leggo', 'ho letto',
    'giornale', 'notizie', 'articolo', 'articoli',
    'scrivendo', 'scrivere', 'scrivo', 'ho scritto',
    'diario', 'scrivo diario', 'sto scrivendo diario',
    'prendo appunti', 'sto prendendo appunti',
    'chiamata', 'telefonata', 'videochiamata',
    'chatto', 'chattare', 'chiacchiero', 'chiacchierare',
    'uscita', 'uscire', 'uscendo',
    'incontro', 'incontrare', 'incontrando',
    'appuntamento', 'festa', 'karaoke',
    'gioco da tavolo', 'giochi da tavolo',
    'bar', 'caffè', 'spuntino',
    'codice', 'programmazione', 'debug', 'debuggando',
    'revisiono', 'revisionare', 'revisionando',
    'rispondo', 'rispondere', 'rispondendo',
    'aggiorno', 'aggiornare', 'aggiornando',
    'preparo', 'preparare', 'preparando',
    'rilascio', 'rilasciato', 'pubblico', 'pubblicato', 'inviare', 'inviando', 'inviato',
    'email', 'mail', 'presentazione', 'slide', 'roadmap', 'report', 'documento', 'ticket',
    'calcio', 'basket', 'pallavolo', 'tennis', 'badminton',
    'escursione', 'trekking', 'bici', 'bicicletta', 'pedalare', 'pedalando',
    'yoga', 'stretch',
    'videogioco', 'videogiochi', 'giocando', 'gioco',
    'film', 'serie', 'streaming',
    'mostra', 'museo',
    'anime', 'manga', 'romanzo', 'libro',
    'musica', 'canzone', 'concerto',
    'podcast', 'livestream', 'youtube',
    'visita medica', 'dentista',
    'pagare bollette', 'pagando bollette',
    'finanza aziendale', 'statistica',
    'allenandomi', 'palestra',
  ],
  verbs: [],
};
