// DOC-DEPS: LLM.md -> docs/ACTIVITY_LEXICON.md
//
// English activity lexicon.
// Extracted from liveInputRules.en.ts.

import type { ActivityLexicon } from './types';

export const enActivityLexicon: ActivityLexicon = {
  strongPhrases: [
    'work', 'working', 'worked',
    'task', 'tasks',
    'study', 'studying', 'studied',
    'learning',
    'meet', 'meeting',
    'standup', 'daily standup',
    'run', 'running', 'ran',
    'walk', 'walking', 'walked',
    'exercise', 'exercising',
    'gym', 'workout',
    'yoga', 'pilates',
    'meditation', 'meditating',
    'breakfast', 'lunch', 'dinner', 'brunch', 'meal',
    'shopping', 'grocery', 'groceries',
    'clean', 'cleaning', 'laundry', 'chores',
    'commute', 'commuting', 'drive', 'driving', 'taxi', 'subway', 'bus', 'train',
    'reading', 'read',
    'writing', 'write',
    'report', 'reports',
    'presentation', 'presentations',
    'slides',
    'email', 'emails', 'mail',
    'ticket', 'tickets',
    'call', 'calling', 'video call',
    'code', 'coding', 'coded',
    'debug', 'debugging',
    'fix', 'fixing',
    'deploy', 'deploying', 'deployed',
    'push', 'pushing', 'pushed',
    'commit', 'committing', 'committed',
    'ship', 'shipped', 'shipping',
    'release', 'released', 'releasing',
    'cook', 'cooking', 'cooked',
    'swim', 'swimming',
    'hike', 'hiking',
    'cycle', 'cycling', 'bike', 'biking',
    'play', 'playing', 'games', 'gaming',
    'movie', 'movies', 'film',
    'anime', 'manga', 'reading comic',
    'music', 'song', 'playlist',
    'podcast', 'listening to',
    'doctor appointment', 'dentist appointment',
    'pay bills', 'paying bills', 'paid bills',
    'exhibition', 'museum',
    'stream', 'livestream', 'youtube', 'shorts',
  ],
  verbs: [],
};
