// DOC-DEPS: LLM.md -> docs/ACTIVITY_LEXICON.md
//
// Italian activity lexicon.
// Extracted from liveInputRules.it.ts.

import type { ActivityLexicon } from './types';

export const itActivityLexicon: ActivityLexicon = {
  strongPhrases: [
    'lavoro', 'lavorare', 'lavorando', 'ho lavorato',
    'sto lavorando',
    'studio', 'studiare', 'studiando', 'ho studiato',
    'ripasso', 'ripassando',
    'riunione', 'meeting', 'standup',
    'riunione con',
    'riunione di',
    'riunione per',
    'correndo', 'ho corso', 'corsa',
    'camminando', 'camminata', 'passeggiata',
    'cammino', 'camminare',
    'nuoto', 'nuotando',
    'nuotare',
    'allenamento', 'palestra', 'fitness',
    'yoga', 'pilates', 'stretching',
    'meditazione', 'meditando',
    'pranzo', 'cena', 'colazione', 'pasto',
    'spesa', 'supermercato', 'grocery',
    'spesa alimentare',
    'lavatrice', 'piatti', 'pulisco', 'pulire', 'pulizie',
    'lavare i piatti', 'cucinare', 'sto cucinando', 'immondizia', 'buttare la spazzatura',
    'ho comprato',
    'pendolare', 'pendolando', 'metro', 'autobus', 'treno', 'guida', 'guidando',
    'lettura', 'leggere', 'leggendo', 'leggo', 'ho letto',
    'giornale', 'notizie', 'articolo', 'articoli',
    'scrivendo', 'scrivere', 'scrivo', 'ho scritto',
    'diario', 'scrivo diario', 'sto scrivendo diario',
    'prendo appunti', 'sto prendendo appunti',
    'chiamata', 'telefonata', 'videochiamata',
    'chatto', 'chattare', 'chiacchiero', 'chiacchierare',
    'uscita', 'uscire', 'uscendo',
    'incontro', 'incontrare', 'incontrando',
    'appuntamento', 'festa', 'karaoke',
    'gioco da tavolo', 'giochi da tavolo',
    'bar', 'caffè', 'spuntino',
    'codice', 'programmazione', 'debug', 'debuggando',
    'revisiono', 'revisionare', 'revisionando',
    'rispondo', 'rispondere', 'rispondendo',
    'aggiorno', 'aggiornare', 'aggiornando',
    'preparo', 'preparare', 'preparando',
    'rilascio', 'rilasciato', 'pubblico', 'pubblicato', 'inviare', 'inviando', 'inviato',
    'email', 'mail', 'presentazione', 'slide', 'roadmap', 'report', 'documento', 'ticket',
    'calcio', 'basket', 'pallavolo', 'tennis', 'badminton',
    'escursione', 'trekking', 'bici', 'bicicletta', 'pedalare', 'pedalando',
    'yoga', 'stretch',
    'videogioco', 'videogiochi', 'giocando', 'gioco',
    'film', 'serie', 'streaming',
    'mostra', 'museo',
    'anime', 'manga', 'romanzo', 'libro',
    'musica', 'canzone', 'concerto',
    'podcast', 'livestream', 'youtube',
    'visita medica', 'dentista',
    'pagare bollette', 'pagando bollette',
    'finanza aziendale', 'statistica',
    'allenandomi', 'palestra',
  ],
  verbs: [],
};
