// DOC-DEPS: LLM.md -> docs/ACTIVITY_LEXICON.md
//
// English activity lexicon.
// Extracted from liveInputRules.en.ts.

import type { ActivityLexicon } from './types.js';

export const enActivityLexicon: ActivityLexicon = {
  strongPhrases: [
    'work', 'working', 'worked',
    'task', 'tasks',
    'doc', 'docs', 'deck', 'decks', 'inbox', 'update', 'updates',
    'study', 'studying', 'studied',
    'learning',
    'meet', 'meeting', 'meetings',
    'standup', 'daily standup', 'sync', '1:1', '1:1s', 'one-on-one', 'one-on-ones',
    'run', 'running', 'ran',
    'walk', 'walking', 'walked',
    'exercise', 'exercising',
    'gym', 'workout',
    'class', 'classes', 'lecture', 'lab', 'homework', 'paper', 'assignment', 'flashcards', 'anki',
    'yoga', 'pilates',
    'meditation', 'meditating',
    'breakfast', 'lunch', 'dinner', 'brunch', 'meal',
    'drink water', 'drinking water', 'hydrate', 'hydrating',
    'drink tea', 'make tea', 'brew tea', 'make coffee', 'brew coffee',
    'fill water bottle', 'refill water bottle',
    'boil water', 'boiled water', 'boiling water',
    'cook rice', 'cooked rice', 'steam rice', 'wash rice',
    'cook breakfast', 'cook lunch', 'cook dinner', 'cook at home',
    'prepare meal', 'meal prep', 'food prep', 'prep ingredients',
    'make soup', 'made soup', 'make porridge', 'cook noodles', 'chop vegetables', 'wash vegetables',
    'grocery shopping', 'go grocery shopping', 'go to market',
    'buy groceries', 'bought groceries', 'buy vegetables', 'buy fruits', 'buy milk', 'buy bread', 'buy eggs',
    'restock groceries', 'restock supplies',
    'shopping', 'grocery', 'groceries',
    'clean', 'cleaning', 'laundry', 'chores',
    'do dishes', 'wash dishes', 'dishes', 'shower', 'bed', 'order', 'take out trash',
    'vacuum', 'mop floor', 'wipe table', 'tidy room',
    'make bed', 'change bedsheets', 'fold clothes', 'hang laundry', 'do laundry', 'air dry clothes',
    'commute', 'commuting', 'drive', 'driving', 'taxi', 'subway', 'bus', 'train',
    'reading', 'read',
    'writing', 'write',
    'report', 'reports',
    'presentation', 'presentations',
    'slides',
    'email', 'emails', 'mail',
    'ticket', 'tickets',
    'call', 'calling', 'called', 'video call',
    'code', 'coding', 'coded',
    'debug', 'debugging',
    'fix', 'fixing',
    'deploy', 'deploying', 'deployed',
    'push', 'pushing', 'pushed',
    'commit', 'committing', 'committed',
    'ship', 'shipped', 'shipping',
    'release', 'released', 'releasing',
    'cook', 'cooking', 'cooked',
    'swim', 'swimming',
    'hike', 'hiking',
    'cycle', 'cycling', 'bike', 'biking',
    'play', 'playing', 'games', 'gaming',
    'movie', 'movies', 'film',
    'anime', 'manga', 'reading comic',
    'music', 'song', 'playlist',
    'podcast', 'listening to',
    'doctor appointment', 'dentist appointment',
    'pay bills', 'paying bills', 'paid bills',
    'exhibition', 'museum',
    'date', 'family', 'friend', 'friends', 'sprint', 'quiz', 'test', 'midterm', 'final', 'deadlift',
    'stream', 'livestream', 'youtube', 'shorts',
    'nap', 'napping', 'resting',
    'skincare', 'morning routine', 'night routine',
    'binge watching', 'binge-watching',
    'hit the gym', 'hit the pool',
    'hopped on a call', 'jumped on a call',
    'ran errands', 'errands',
    'haircut', 'massage', 'checkup', 'physical',
    'takeout', 'delivery', 'ordered food',
    'batch cooking', 'meal prepped',
    // strength / gym movements
    'lift', 'lifting', 'lifted',
    'squat', 'squatting', 'squats',
    'bench press', 'bench pressing', 'benching',
    'deadlift', 'deadlifting',
    'row', 'rowing',
    'pull-ups', 'push-ups', 'pushups', 'pullups', 'chin-ups',
    'leg day', 'upper body', 'core workout',
    // outdoor / adventure sports
    'climb', 'climbing', 'climbed',
    'boulder', 'bouldering',
    'surf', 'surfing', 'surfed',
    'ski', 'skiing', 'skied',
    'snowboard', 'snowboarding',
    'skate', 'skating', 'skateboard', 'skateboarding',
    'golf', 'golfing',
    'bowl', 'bowling',
    // martial arts / combat
    'boxing', 'box',
    'kickboxing',
    'martial arts', 'judo', 'bjj', 'muay thai', 'wrestling',
    'sparring',
    // creative & hobbies
    'journal', 'journaling', 'journaled',
    'sketch', 'sketching', 'sketched',
    'draw', 'drawing', 'drew',
    'paint', 'painting', 'painted',
    'craft', 'crafting',
    'knit', 'knitting',
    'sew', 'sewing',
    'bake', 'baking', 'baked',
    'garden', 'gardening',
    'photography', 'photographing',
    // professional / work extras
    'brainstorm', 'brainstorming', 'brainstormed',
    'design', 'designing', 'designed',
    'edit', 'editing', 'edited',
    'proofread', 'proofreading',
    'interview', 'interviewing', 'interviewed',
    'prototype', 'prototyping',
    'network', 'networking',
    'freelance', 'freelancing',
    'intern', 'interning',
    'research', 'researching', 'researched',
    // wellness / mindfulness
    'breathwork', 'breathing exercises',
    'therapy', 'therapist', 'counseling', 'counselling',
    'journaling',
    'fasting', 'intermittent fasting',
    // travel / errands
    'travel', 'traveling', 'travelling', 'traveled', 'travelled',
    'trip', 'flight', 'road trip',
    'pack', 'packing', 'packed',
    'unpack', 'unpacking',
    'move', 'moving house',
    'dry cleaning', 'pharmacy', 'bank',
    // volunteer / social good
    'volunteer', 'volunteering', 'volunteered',
    'donate', 'donating', 'donated',
    'tutor', 'tutoring',
  ],
  verbs: [],
  phrasePatterns: [
    /\b(i am|i'm|im)\s+(working|studying|coding|running|walking|cooking)\b/i,
    /\b(working|studying|coding|running|walking|cooking)\s+(now|right now)\b/i,
    /\b(study|studying|review|reviewing|learn|learning)\s+(?!about\s+to\b|how\s+to\b)([a-z][a-z0-9-]*(\s+[a-z][a-z0-9-]*){0,3})\b/i,
    /\b(just\s+)?(had|did|wrapped\s+up)\s+(a\s+)?(meeting|workout|class|call)\b/i,
    /\b(just\s+)?got\s+home\b/i,
    /\b(went|headed\s+out)\s+for\s+(a\s+)?(run|walk)\b/i,
    /\b(out\s+for\s+(a\s+)?coffee)\b/i,
    /\b(grabbing|grabbed|having|had)\s+(a\s+)?coffee\b/i,
    /\b(writing|working\s+on|reviewing)\s+(the\s+)?(report|doc|assignment|ticket|code)\b/i,
    /\b(sending|replying\s+to|answering)\s+(emails?|messages?)\b/i,
    /\b(preparing|building|drafting|updating)\s+(a\s+|the\s+)?(presentation|slides|roadmap|report|doc|deck)\b/i,
    /\b(deep\s+in|buried\s+in)\s+(a\s+|the\s+|my\s+)?(doc|deck|report|paperwork|spreadsheet|inbox)\b/i,
    /\b(finishing\s+up|wrapping\s+up|polishing)\s+(a\s+|the\s+|my\s+)?(deck|doc|report|paper|slides?)\b/i,
    /\b(doing|having|in)\s+(a\s+)?(1:1|1:1s|one-on-one|one-on-ones|one\s+on\s+one|one\s+on\s+ones|sync|sync-up)\b/i,
    /\b(in\s+(a\s+)?)sync\b/i,
    /\b(grinding\s+through|working\s+through)\s+(my\s+)?(inbox|emails?)\b/i,
    /\b(just\s+)?sent\s+(the\s+|my\s+)?((weekly|status)\s+)?(update|report|deck|slides?|doc|paper)\b/i,
    /\b(debugging|fixing|testing)\b/i,
    /\b(just\s+)?(pushed|shipped|deployed|released)\s+(a\s+|the\s+)?(fix|feature|update)\b/i,
    /\b(driving|taking)\s+(a\s+)?(taxi|bus|train|subway)\b/i,
    /\b(commuting|on\s+the\s+way\s+to)\s+(work|office|school|gym)\b/i,
    /\b(doing|finished|did)\s+(the\s+)?(laundry|cleaning|dishes|meal\s+prep|grocery\s+shopping)\b/i,
    /\b(doing|working\s+on)\s+(my\s+)?homework\b/i,
    /\b(cramming)\s+for\s+(my\s+|the\s+)?(exam|quiz|test|midterm|final)\b/i,
    /\b(in|at)\s+(class|lecture|lab)\b/i,
    /\b(doing|reviewing)\s+(anki\s+)?flashcards\b/i,
    /\b(office\s+hours?)\b/i,
    /\b(taking|took)\s+(a\s+)?shower\b/i,
    /\b(just\s+)?woke\s+up\b/i,
    /\b(getting|got)\s+ready\s+for\s+bed\b/i,
    /\b(picking\s+up|picked\s+up)\s+(my\s+)?order\b/i,
    /\b(playing|played)\s+(football|soccer|basketball|badminton|tennis|ping\s+pong)\b/i,
    /\b(swimming|hiking|cycling|biking|doing\s+yoga|doing\s+pilates|stretching)\b/i,
    /\b(did|ran)\s+(a\s+)?\d+(k|km|mile|miles)\b/i,
    /\b(leg\s+day)\b/i,
    /\b(pr['’]?d)\s+(on\s+)?(deadlift|squat|bench)\b/i,
    /\b(watching|watched)\s+(a\s+)?(movie|series|tv\s+show|livestream)\b/i,
    /\b(listening\s+to)\s+(a\s+)?(podcast|music)\b/i,
    /\b(hanging\s+out|meeting|met|visiting|visited)\s+(friends|family)\b/i,
    /\b(catching\s+up)\s+with\s+(family|friends?)\b/i,
    /\b(calling|called)\s+(my\s+)?(mom|mother|dad|father|parents?|family|friend|friends)\b/i,
    /\b(on\s+(a\s+)?)date\b/i,
    /\b(met)\s+(an?\s+old\s+)?friend\b/i,
    /\b(went\s+to)\s+(a\s+)?(concert|museum|exhibition|cafe)\b/i,
    /\b(karaoke|board\s+games?|game\s+night|date\s+night)\b/i,
    /\b(chatting|chatted)\s+with\b/i,
    /\b(hanging\s+out|hung\s+out)\b/i,
    /\b(grabbing|grabbed|having|had)\s+(breakfast|lunch|dinner|brunch)\b/i,
    /\b(waiting\s+in\s+line)\b/i,
    /\b(back[-\s]?to[-\s]?back)\s+meetings\b/i,
    /\b(reading|read|finished\s+reading)\s+(a\s+)?(book|novel|chapter)\b/i,
    /\b(watching|watched|reading|read)\s+(anime|manga|novel|novels)\b/i,
    /\b(reading|read|skimming|skimmed)\s+(the\s+)?(newspaper|news|article|articles)\b/i,
    /\b(journaling|journaled|writing|wrote)\s+(a\s+)?(journal|diary|journal\s+entry)\b/i,
    /\b(taking|took|reviewing)\s+(notes|meeting\s+notes|class\s+notes)\b/i,
    /\b(doctor|dentist)\s+(appointment|visit)\b/i,
    /\b(paying|paid)\s+(the\s+)?(bills?|rent|utilities)\b/i,
    /\b(gaming|playing\s+games|played\s+games)\b/i,
    /\b(on\s+my\s+way\s+to|at)\s+(the\s+)?(office|gym|school)\b/i,
    /\b(in|on)\s+(a\s+)?meeting\b/i,
    /\bvideo\s+call\b/i,
    /\b(pulled\s+an\s+all[-\s]?nighter)\b/i,
    /\b(got\s+promoted)\b/i,
    /\b(wrapped\s+(the\s+)?)sprint\b/i,
    /\b(bombed|aced)\s+(that\s+|the\s+|my\s+)?(quiz|test|exam|midterm|final|presentation)\b/i,
    /\b(meal\s+prepped|batch\s+cooked)\b/i,
    /\b(hit\s+(the\s+)?(gym|pool|track))\b/i,
    /\b(took\s+(a\s+)?(nap|break|walk))\b/i,
    /\b(had\s+(a\s+)?(nap|rest))\b/i,
    /\b(hopped\s+on\s+(a\s+)?(call|zoom|meet))\b/i,
    /\b(jumped\s+on\s+(a\s+)?(call|zoom|meet))\b/i,
    /\b(got\s+(a\s+)?(haircut|massage|checkup|physical))\b/i,
    /\b(ran\s+(some\s+)?(errands?))\b/i,
    /\b(knocked\s+out\s+(the\s+|my\s+)?(workout|run|chores))\b/i,
    /\b(binge(d|[- ]watching)?)\s+(a\s+|the\s+)?(show|series|season|anime)\b/i,
    /\b(ordered\s+(food|takeout|delivery|pizza|sushi))\b/i,
    /\b(went\s+for\s+(a\s+)?(swim|hike|drive|ride))\b/i,
    /\b(did\s+(my\s+)?(skincare|morning\s+routine|night\s+routine))\b/i,
    // strength training
    /\b(did\s+(some\s+)?(lifting|squats|pull-ups|push-ups|deadlifts|rows))\b/i,
    /\b(hit\s+(a\s+)?new\s+pr|set\s+a\s+new\s+pr)\b/i,
    // creative hobbies
    /\b(did\s+some\s+)?(journaling|sketching|drawing|painting|crafting|knitting|sewing|baking|gardening)\b/i,
    /\b(played\s+(the\s+)?(guitar|piano|violin|bass|drums|keyboard|ukulele))\b/i,
    // travel
    /\b(just\s+)?(landed|arrived|got\s+back|touched\s+down)\b/i,
    /\b(packed\s+(my\s+)?(bag|bags|suitcase))\b/i,
    /\b(on\s+(a\s+)?trip|going\s+on\s+a\s+trip|took\s+a\s+trip)\b/i,
    /\b(at\s+the\s+airport|on\s+(the\s+)?flight|on\s+the\s+plane)\b/i,
    // wellness
    /\b(had\s+(a\s+)?therapy\s+session|went\s+to\s+therapy)\b/i,
    /\b(did\s+(some\s+)?breathwork|breathing\s+exercises)\b/i,
    // extra social / life
    /\b(volunteered|did\s+volunteer\s+work)\b/i,
    /\b(went\s+to\s+(the\s+)?(pharmacy|bank|post\s+office|dry\s+cleaner))\b/i,
    /\b(picked\s+up\s+(my\s+)?(prescription|meds|medicine))\b/i,
  ],
};
