/**
 * install-hooks.mjs
 * 将 git hook 脚本安装到 .git/hooks/ 目录。
 * 运行：node ./scripts/install-hooks.mjs
 *
 * 安装后效果：每次 git commit 时自动触发 pre-commit.mjs。
 * Windows 下 git 使用 bash 脚本，本脚本会生成对应的 shell 包装。
 */

import { writeFile, mkdir, chmod } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');

function resolveHooksDir() {
    try {
        const hooksPath = execFileSync('git', ['rev-parse', '--git-path', 'hooks'], {
            cwd: root,
            encoding: 'utf8',
        }).trim();
        if (!hooksPath) {
            throw new Error('empty git hooks path');
        }
        return path.isAbsolute(hooksPath) ? hooksPath : path.resolve(root, hooksPath);
    } catch (error) {
        console.error('[install-hooks] Failed to resolve git hooks path. Are you in a git repository?');
        throw error;
    }
}

// hook名称 → 对应脚本
const HOOKS = {
    'pre-commit': 'scripts/pre-commit.mjs',
};

async function main() {
    const hooksDir = resolveHooksDir();

    await mkdir(hooksDir, { recursive: true });

    for (const [hookName, scriptPath] of Object.entries(HOOKS)) {
        const hookFile = path.join(hooksDir, hookName);

        // Git hooks 在 Windows 上也是 bash 脚本（Git for Windows 内置 bash）
        const hookContent = `#!/usr/bin/env sh
# Auto-generated by scripts/install-hooks.mjs — do not edit manually.
# Re-run: node ./scripts/install-hooks.mjs
node "${scriptPath.replace(/\\/g, '/')}"
`;

        await writeFile(hookFile, hookContent, { encoding: 'utf8' });

        // Unix 权限（Windows 上 git bash 也需要 +x）
        try {
            await chmod(hookFile, 0o755);
        } catch {
            // Windows 上 chmod 可能无效，git bash 会忽略权限位，无需处理
        }

        console.log(`[install-hooks] ✓ Installed: ${path.join(hooksDir, hookName)} → ${scriptPath}`);
    }

    console.log('\n[install-hooks] Done. Hooks will run automatically on git commit.\n');
    console.log('To test without committing:');
    console.log('  node ./scripts/pre-commit.mjs\n');
}

main().catch(err => {
    console.error('[install-hooks] Error:', err);
    process.exit(1);
});
