// DOC-DEPS: LLM.md -> docs/ACTIVITY_MOOD_AUTO_RECOGNITION.md -> src/features/chat/README.md

export const IT_ACTIVITY_VERBS = [
  'studio',
  'studiare',
  'studiando',
  'ho studiato',
  'ripasso',
  'ripassando',
  'lavoro',
  'lavorare',
  'lavorando',
  'ho lavorato',
  'sto lavorando',
  'riunione',
  'meeting',
  'standup',
  'daily standup',
  'corro',
  'correre',
  'correndo',
  'ho corso',
  'cammino',
  'camminare',
  'camminando',
  'scrivo',
  'scrivere',
  'scrivendo',
  'ho scritto',
  'revisiono',
  'revisionare',
  'revisionando',
  'rispondo',
  'rispondere',
  'rispondendo',
  'aggiorno',
  'aggiornare',
  'aggiornando',
  'preparo',
  'preparare',
  'preparando',
  'debug',
  'debuggando',
  'correzione',
  'rilascio',
  'rilasciato',
  'pubblico',
  'pubblicato',
  'inviare',
  'inviando',
  'inviato',
  'email',
  'mail',
  'presentazione',
  'slide',
  'roadmap',
  'report',
  'documento',
  'codice',
  'ticket',
  'allenamento',
  'palestra',
  'stretching',
  'stretch',
  'yoga',
  'pilates',
  'nuoto',
  'nuotare',
  'nuotando',
  'escursione',
  'camminata',
  'trekking',
  'bici',
  'bicicletta',
  'pedalare',
  'pedalando',
  'calcio',
  'basket',
  'pallavolo',
  'tennis',
  'badminton',
  'spesa',
  'supermercato',
  'spesa alimentare',
  'lavatrice',
  'lavare i piatti',
  'pulizie',
  'pulire',
  'cucinare',
  'sto cucinando',
  'immondizia',
  'buttare la spazzatura',
  'ho comprato',
  'chiamata',
  'telefonata',
  'messaggio',
  'messaggi',
  'scrivendo a',
  'videochiamata',
  'chatto',
  'chattare',
  'chiacchiero',
  'chiacchierare',
  'uscita',
  'uscire',
  'uscendo',
  'incontro',
  'incontrare',
  'incontrando',
  'appuntamento',
  'festa',
  'karaoke',
  'gioco da tavolo',
  'giochi da tavolo',
  'pranzo',
  'cena',
  'colazione',
  'spuntino',
  'caffè',
  'bar',
  'anime',
  'manga',
  'romanzo',
  'film',
  'serie',
  'concerto',
  'mostra',
  'museo',
  'podcast',
  'streaming',
  'videogioco',
  'videogiochi',
];

export const IT_MOOD_WORDS = [
  'stanco',
  'stanca',
  'stressato',
  'stressata',
  'ansioso',
  'ansiosa',
  'triste',
  'felice',
  'contento',
  'contenta',
  'calmo',
  'calma',
  'arrabbiato',
  'arrabbiata',
  'esausto',
  'esausta',
  'sollevato',
  'sollevata',
  'confuso',
  'confusa',
  'sollievo',
  'pesante',
  'faticoso',
  'stremato',
  'stremata',
  'scarico',
  'scarica',
  'sereno',
  'serena',
  'bene',
  'male',
  'ok',
];

export const IT_MOOD_PATTERNS = [
  /\b(mi\s+sento|sono)\s+(molto\s+|troppo\s+|davvero\s+)?(stanco|stanca|stressato|stressata|ansioso|ansiosa|triste|felice|calmo|calma|arrabbiato|arrabbiata|esausto|esausta|sollevato|sollevata)\b/i,
  /\b(era|e\s+stata|e\s+stato|andata)\s+(stressante|pesante|ottima|bene|male)\b/i,
  /\bmi\s+ha\s+(stressato|stressata|confuso|confusa|stancato|stancata)\b/i,
  /\bmi\s+ha\s+dato\s+sollievo\b/i,
  /\b(mi\s+sento|sono)\s+(un\s+po'\s+|molto\s+)?(bene|male|scarico|scarica|sereno|serena)\b/i,
  /\b(e|è)\s+(molto\s+|davvero\s+)?(faticoso|pesante|stressante)\b/i,
];

export const IT_ACTIVITY_PATTERNS = [
  /\b(sto|stavo)\s+(studiando|lavorando|correndo|camminando|scrivendo)\b/i,
  /\b(sto|stavo)\s+(revisionando|rispondendo|preparando|aggiornando|debuggando)\b/i,
  /\b(studio|sto\s+studiando|ripasso|sto\s+ripassando|imparo|sto\s+imparando)\s+(?!come\s+fare\b)([a-z\u00c0-\u017f][a-z\u00c0-\u017f0-9-]*(\s+[a-z\u00c0-\u017f][a-z\u00c0-\u017f0-9-]*){0,3})\b/i,
  /\b(revisiono|sto\s+revisionando|rispondo|sto\s+rispondendo|preparo|sto\s+preparando|aggiorno|sto\s+aggiornando)\s+(a|il|la|alle|ai)?\s*(email|mail|presentazione|slide|roadmap|report|documento|ticket|codice)\b/i,
  /\b(ho\s+appena\s+)?(fatto|finito)\s+(la\s+)?(riunione|chiamata|spesa|lezione|corsa)\b/i,
  /\b(sto\s+scrivendo|sto\s+lavorando\s+su)\s+(il\s+)?(report|documento|compito|codice)\b/i,
  /\b(ho\s+appena\s+)?(pubblicato|rilasciato|inviato)\s+(una\s+|il\s+)?(correzione|feature|aggiornamento|report|documento)\b/i,
  /\b(sto|stavo)\s+(guidando|prendendo)\s+(la\s+)?(macchina|metro|autobus|treno|taxi)\b/i,
  /\b(sono|sto)\s+(in\s+)?(metro|autobus|treno|macchina|ufficio|palestra|supermercato)\b/i,
  /\b(sto|ho\s+)?(facendo|fatto|finito)\s+(la\s+)?(spesa|lavatrice|pulizie|cena|pranzo|colazione)\b/i,
  /\b(sto|ho\s+)?(lavando|lavato)\s+(i\s+)?piatti\b/i,
  /\b(sto|ho\s+)?(nuotando|nuotato|pedalando|pedalato|camminando|fatto\s+trekking|fatto\s+yoga)\b/i,
  /\b(gioco|sto\s+giocando|ho\s+giocato)\s+(a\s+)?(calcio|basket|tennis|badminton|pallavolo)\b/i,
  /\b(sto|ho\s+)?(guardando|visto)\s+(un\s+)?(film|serie|streaming)\b/i,
  /\b(sto|ho\s+)?(ascoltando|ascoltato)\s+(un\s+)?podcast\b/i,
  /\b(sto|ho\s+)?(uscendo|uscito|incontrando|incontrato)\s+(con\s+)?(amici|famiglia)\b/i,
  /\b(sono\s+andato|vado|sto\s+andando)\s+(al\s+|alla\s+)?(concerto|mostra|museo|bar)\b/i,
  /\b(karaoke|giochi\s+da\s+tavolo|serata\s+giochi)\b/i,
  /\b(chatto|sto\s+chattando|chiacchiero|sto\s+chiacchierando)\s+(con\s+.+)?\b/i,
  /\b(prendo|ho\s+preso|sto\s+prendendo|faccio|ho\s+fatto)\s+(colazione|pranzo|cena)\b/i,
  /\b(guardo|sto\s+guardando|ho\s+guardato)\s+(anime|serie|film)\b/i,
  /\b(leggo|sto\s+leggendo|ho\s+letto)\s+(manga|romanzo|libro)\b/i,
  /\b(videogioco|sto\s+giocando|ho\s+giocato)\b/i,
  /\b(in\s+ufficio|in\s+palestra|a\s+scuola)\b/i,
  /\b(in|alla)\s+riunione\b/i,
  /\b(videochiamata|chiamata)\b/i,
];

export const IT_STRONG_COMPLETION_PATTERNS = [
  /\b(ho\s+)?(finito|completato)\b/i,
  /\bappena\s+finito\b/i,
  /\b(ho\s+)?(chiuso|terminato)\s+(la\s+)?(riunione|chiamata|lezione|sessione)\b/i,
  /\b(ho\s+)?(inviato)\s+(il\s+)?(report|documento)\b/i,
  /\b(finalmente\s+)?(rilasciato|pubblicato|spedito)\b/i,
  /\bho\s+finito\s+le\s+slide\b/i,
];

export const IT_FUTURE_OR_PLAN_PATTERNS = [
  /\b(domani|dopo|piu\s+tardi|tra\s+poco|stasera|prossim[oa])\b/i,
  /\b(voglio|vorrei|devo|andr[oò]|sto\s+per|andr[oò]\s+a|ho\s+intenzione\s+di)\b/i,
];

export const IT_LAST_ACTIVITY_REFERENCES = [
  'quello',
  'quella',
  'prima',
  'quella riunione',
  'riunione di prima',
  'quella chiamata',
  'quella lezione',
  'quel lavoro',
  'quella sessione',
  'la chiamata di prima',
  'quella cosa che ho fatto',
  'quella cosa',
];
