// DOC-DEPS: LLM.md -> docs/ACTIVITY_MOOD_AUTO_RECOGNITION.md -> src/features/chat/README.md

export const EN_ACTIVITY_VERBS = [
  'work',
  'working',
  'worked',
  'task',
  'tasks',
  'study',
  'studying',
  'studied',
  'learning',
  'meet',
  'meeting',
  'standup',
  'daily standup',
  'run',
  'running',
  'ran',
  'walk',
  'walking',
  'code',
  'coding',
  'coded',
  'debug',
  'debugging',
  'fix',
  'fixing',
  'ship',
  'shipping',
  'shipped',
  'deploy',
  'deploying',
  'deployed',
  'release',
  'releasing',
  'released',
  'push',
  'pushing',
  'pushed',
  'commit',
  'committing',
  'committed',
  'cook',
  'cooking',
  'cooked',
  'write',
  'writing',
  'wrote',
  'reading',
  'read',
  'report',
  'reports',
  'presentation',
  'presentations',
  'slides',
  'email',
  'emails',
  'mail',
  'message',
  'messages',
  'roadmap',
  'ticket',
  'tickets',
  'pr',
  'pull request',
  'doc',
  'docs',
  'document',
  'documentation',
  'assignment',
  'review',
  'reviewing',
  'reviewed',
  'testing',
  'tested',
  'workout',
  'exercise',
  'exercising',
  'gym',
  'stretch',
  'stretching',
  'yoga',
  'pilates',
  'swim',
  'swimming',
  'hike',
  'hiking',
  'bike',
  'biking',
  'cycle',
  'cycling',
  'football',
  'soccer',
  'basketball',
  'badminton',
  'tennis',
  'ping pong',
  'table tennis',
  'commute',
  'commuting',
  'drive',
  'driving',
  'taxi',
  'subway',
  'bus',
  'train',
  'shopping',
  'grocery',
  'groceries',
  'supermarket',
  'laundry',
  'cleaning',
  'clean',
  'washed dishes',
  'dishes',
  'trash',
  'cooking dinner',
  'meal prep',
  'bought',
  'call',
  'calling',
  'texting',
  'texted',
  'messaging',
  'facetime',
  'chat',
  'chatting',
  'hang out',
  'hanging out',
  'meet friends',
  'visited',
  'visiting',
  'date',
  'dating',
  'party',
  'karaoke',
  'board game',
  'board games',
  'lunch',
  'breakfast',
  'dinner',
  'snack',
  'coffee',
  'cafe',
  'anime',
  'manga',
  'novel',
  'movie',
  'movies',
  'series',
  'tv show',
  'concert',
  'exhibition',
  'museum',
  'podcast',
  'livestream',
  'gaming',
  'game',
];

export const EN_MOOD_WORDS = [
  'tired',
  'exhausted',
  'stressed',
  'stressful',
  'anxious',
  'sad',
  'down',
  'upset',
  'frustrated',
  'annoyed',
  'drained',
  'relieved',
  'happy',
  'glad',
  'calm',
  'angry',
  'overwhelmed',
  'pointless',
  'tedious',
  'heavy',
  'burned out',
  'burnt out',
  'worn out',
  'fatigued',
  'relax',
  'relaxed',
  'okay',
  'ok',
  'good',
  'great',
  'rough',
  'smooth',
  'relief',
  'light',
  'lighter',
];

export const EN_MOOD_PATTERNS = [
  /\b(feel|feeling)\s+(very\s+|so\s+|really\s+)?(tired|exhausted|stressed|stressful|anxious|sad|down|happy|calm|angry|overwhelmed|drained|relieved|frustrated|annoyed)\b/i,
  /\b(so|very|really|quite)\s+(tired|exhausted|stressed|stressful|anxious|sad|happy|calm|angry|frustrated|drained|relieved)\b/i,
  /\b(was|is|felt|feels)\s+(stressful|annoying|great|awful|rough|smooth)\b/i,
  /\b(was|is|felt|feels)\s+pointless\b/i,
  /\bmade\s+me\s+(anxious|stressed|upset|angry)\b/i,
  /\b(feels?|felt)\s+like\s+(a\s+)?(weight\s+off|relief)\b/i,
  /\b(is|was|feels?|felt)\s+(so\s+|very\s+|really\s+)?(tedious|heavy|draining|rough|smooth)\b/i,
  /\b(weight\s+off\s+my\s+shoulders?)\b/i,
];

export const EN_ACTIVITY_PATTERNS = [
  /\b(i am|i'm|im)\s+(working|studying|coding|running|walking|cooking)\b/i,
  /\b(working|studying|coding|running|walking|cooking)\s+(now|right now)\b/i,
  /\b(study|studying|review|reviewing|learn|learning)\s+(?!about\s+to\b|how\s+to\b)([a-z][a-z0-9-]*(\s+[a-z][a-z0-9-]*){0,3})\b/i,
  /\b(just\s+)?(had|did|wrapped\s+up)\s+(a\s+)?(meeting|workout|class|call)\b/i,
  /\b(writing|working\s+on|reviewing)\s+(the\s+)?(report|doc|assignment|ticket|code)\b/i,
  /\b(sending|replying\s+to|answering)\s+(emails?|messages?)\b/i,
  /\b(preparing|building|drafting|updating)\s+(a\s+|the\s+)?(presentation|slides|roadmap|report|doc|deck)\b/i,
  /\b(debugging|fixing|testing)\b/i,
  /\b(just\s+)?(pushed|shipped|deployed|released)\s+(a\s+|the\s+)?(fix|feature|update)\b/i,
  /\b(driving|taking)\s+(a\s+)?(taxi|bus|train|subway)\b/i,
  /\b(commuting|on\s+the\s+way\s+to)\s+(work|office|school|gym)\b/i,
  /\b(doing|finished|did)\s+(laundry|cleaning|dishes|meal\s+prep|grocery\s+shopping)\b/i,
  /\b(playing|played)\s+(football|soccer|basketball|badminton|tennis|ping\s+pong)\b/i,
  /\b(swimming|hiking|cycling|biking|doing\s+yoga|doing\s+pilates|stretching)\b/i,
  /\b(watching|watched)\s+(a\s+)?(movie|series|tv\s+show|livestream)\b/i,
  /\b(listening\s+to)\s+(a\s+)?(podcast|music)\b/i,
  /\b(hanging\s+out|meeting|met|visiting|visited)\s+(friends|family)\b/i,
  /\b(went\s+to|going\s+to)\s+(a\s+)?(concert|museum|exhibition|cafe)\b/i,
  /\b(karaoke|board\s+games?|game\s+night|date\s+night)\b/i,
  /\b(chatting|chatted)\s+with\b/i,
  /\b(hanging\s+out|hung\s+out)\b/i,
  /\b(grabbing|grabbed|having|had)\s+(breakfast|lunch|dinner|brunch)\b/i,
  /\b(watching|watched|reading|read)\s+(anime|manga|novel|novels)\b/i,
  /\b(gaming|playing\s+games|played\s+games)\b/i,
  /\b(on\s+my\s+way\s+to|at)\s+(the\s+)?(office|gym|school)\b/i,
  /\b(in|on)\s+(a\s+)?meeting\b/i,
  /\bvideo\s+call\b/i,
];

export const EN_STRONG_COMPLETION_PATTERNS = [
  /\b(just\s+)?(finished|done|completed)\b/i,
  /\bfinished\s+(the\s+)?(report|meeting|task|workout|class)\b/i,
  /\b(wrapped\s+up|got\s+done\s+with)\s+(the\s+)?(report|meeting|task|class|workout|call)\b/i,
  /\b(sent\s+out\s+the\s+report)\b/i,
  /\b(finally\s+)?(shipped|released|deployed|pushed)\b/i,
  /\b(done\s+for\s+today)\b/i,
];

export const EN_FUTURE_OR_PLAN_PATTERNS = [
  /\b(tomorrow|later|soon|tonight|later\s+today|next\s+(hour|meeting|class|week))\b/i,
  /\b(gonna|going\s+to|plan\s+to|want\s+to|about\s+to|will|need\s+to|have\s+to)\b/i,
];

export const EN_LAST_ACTIVITY_REFERENCES = [
  'that',
  'it',
  'the meeting',
  'that meeting',
  'that task',
  'that call',
  'that report',
  'just now',
  'earlier',
  'earlier one',
  'what i just did',
  'that phone call',
  'that class',
  'that workout',
  'that training',
  'that lesson',
  'the call earlier',
  'the class earlier',
  'the workout earlier',
];
